M48
; DRILL file {KiCad 7.0.7} date 2024 April 21, Sunday 22:48:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-21T22:48:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X93.0Y-142.2
X93.0Y-35.099
X165.778Y-37.599
X165.778Y-66.599
X185.343Y-142.099
T0
M30
